/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ring.glb --transform 
Files: ring.glb [2.83MB] > C:\Users\hi\projects\webgl-jewelery-ring\public\ring-transformed.glb [2.23MB] (21%)
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ring-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={64.983} near={30.494} fov={39.598} position={[0, 1.323, 5.148]} rotation={[-0.262, 0, 0]} scale={0.114} />
      <PerspectiveCamera makeDefault={false} far={74.294} near={39.741} fov={39.598} position={[0.018, 0.491, 6.466]} rotation={[-0.262, 0.003, 0.001]} scale={0.114} />
      <PerspectiveCamera makeDefault={false} far={64.983} near={30.494} fov={39.598} position={[0, 1.323, 5.148]} rotation={[-0.262, 0, 0]} scale={0.114} />
      <mesh geometry={nodes['Metal_01(AEDC52AC-424D-4E51-BD30-021999E6F4F5)'].geometry} material={materials['Metal 01']} position={[0, -0.385, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.114} />
      <mesh geometry={nodes['Diamond_Emerald_Square(D063E76B-FA2F-4C0E-BA35-4FD66D0FD024)'].geometry} material={nodes['Diamond_Emerald_Square(D063E76B-FA2F-4C0E-BA35-4FD66D0FD024)'].material} position={[0, 1.409, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.091, 0.091, 0.088]} />
    </group>
  )
}

useGLTF.preload('/ring-transformed.glb')
